// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/iraunit/open-hearing/api/restHandler"
	"github.com/iraunit/open-hearing/api/router"
	"github.com/iraunit/open-hearing/respository/db"
	"github.com/iraunit/open-hearing/respository/onboardingRepo"
	"github.com/iraunit/open-hearing/service/onboardingService"
)

// Injectors from wire.go:

func InitializeApp() *App {
	pgDB := db.NewPgDb()
	onboardingRepoImpl := onboardingRepo.NewOnboardingRepoImpl(pgDB)
	onboardingServiceImpl := onboardingService.NewOnboardingRestHandler(onboardingRepoImpl)
	onboardingRestHandlerImpl := restHandler.NewOnboardingRestHandler(onboardingServiceImpl)
	muxRouter := router.NewMuxRouter(onboardingRestHandlerImpl)
	app := NewApp(muxRouter)
	return app
}
